steelMemberShearPanel - Types for Steel Design
Dlubal-Software/RFEM_Python_Client pull request #110
Opened 2022-03-22 15:03 UTC by dogukankaratas

- steelMemberShearPanel class has added.
- Enumeration items created. (Some fixes has done in enumeration -there were identical classes, they're removed.)
- Unit test has added.

2022-03-30 10:19 UTC, OndraMichal requested changes

2022-03-30 10:19 UTC, OndraMichal commented on UnitTests/test_steelMemberShearPanel.py
> +from RFEM.enums import *
Please specify the imported enum. I think it should be just one.

2022-03-30 10:19 UTC, OndraMichal commented on RFEM/TypesForSteelDesign/steelMemberShearPanel.py
> +        Args:
I think the argument section could be shorter, not specifying every case. Or at least specify first all arguments and then add any informatio necessary for understanding. I think we don't have to copy whole logic into dosctring. If user wants to know the logic, he ca nread it from the body of the method. 
What do you think?

2022-03-30 10:19 UTC, OndraMichal commented on RFEM/TypesForSteelDesign/steelMemberShearPanel.py
> +                params: dict = {}):
default dict value is now None in the main branch. Then add if before params assignment to clentObject.
```
if params:
    for key in params:
        clientObject[key] = params[key] 
```

2022-03-30 10:19 UTC, OndraMichal commented on UnitTests/test_steelMemberShearPanel.py
> +    Model.clientModel.service.finish_modification()
Add empty line at the end :-)

2022-04-26 13:52 UTC, dogukankaratas commented on UnitTests/test_steelMemberShearPanel.py
> +from RFEM.enums import *
fixed

2022-04-26 13:53 UTC, dogukankaratas commented on UnitTests/test_steelMemberShearPanel.py
> +    Model.clientModel.service.finish_modification()
done

2022-04-26 13:54 UTC, dogukankaratas commented on RFEM/TypesForSteelDesign/steelMemberShearPanel.py
> +        Args:
Can be done, but didn't want to delete when it's already there :) I will be more specific next time.

2022-04-27 05:44 UTC, OndraMichal approved these changes

2022-04-27 05:45 UTC, merged