Ondrej Michal-special objects update
Dlubal-Software/RFEM_Python_Client pull request #135
Opened 2022-05-05 09:14 UTC by OndraMichal

Updated Intersections, Surface Results Adjustments, Surface Contacts, Result Sections, and Structure Modifications.
Test created.

unit tests: 147 passed, 9 skipped in 199.99s

2022-05-10 07:39 UTC, dogukankaratas requested changes
There is a bug for result section in core operations most probably.

2022-05-10 07:39 UTC, dogukankaratas commented on UnitTests/test_SpecialObjects.py
> +    ResultSection(1,ResultSectionType.TYPE_2_POINTS_AND_VECTOR, ResultSectionResultDirection.SHOW_RESULTS_IN_GLOBAL_MINUS_X,True,[1, [1,0,0], [0,2,0], ResultSectionProjection.PROJECTION_IN_VECTOR, [1
Result Section returns an assert.

![image](https://user-images.githubusercontent.com/61163577/167574838-4174bf8a-fcb7-4c75-89ef-9f5da8fd56bf.png)

2022-05-18 11:42 UTC, OndraMichal commented on UnitTests/test_SpecialObjects.py
> +    ResultSection(1,ResultSectionType.TYPE_2_POINTS_AND_VECTOR, ResultSectionResultDirection.SHOW_RESULTS_IN_GLOBAL_MINUS_X,True,[1, [1,0,0], [0,2,0], ResultSectionProjection.PROJECTION_IN_VECTOR, [1
I adjusted for XML restructuring but I see no Assert while testing with latest GM.

2022-05-18 12:08 UTC, OndraMichal commented on UnitTests/test_SpecialObjects.py
> +    ResultSection(1,ResultSectionType.TYPE_2_POINTS_AND_VECTOR, ResultSectionResultDirection.SHOW_RESULTS_IN_GLOBAL_MINUS_X,True,[1, [1,0,0], [0,2,0], ResultSectionProjection.PROJECTION_IN_VECTOR, [1
Seems to be caused by assigned_to_surfaces and assigned_to_solids. Before both True, now True False. Assert doesn't show.

2022-05-18 12:41 UTC, dogukankaratas approved these changes

2022-05-18 12:47 UTC, merged