Tank Web Application
Dlubal-Software/RFEM_Python_Client pull request #184
Opened 2022-10-20 14:55 UTC by dogukankaratas

# Description

A new example which runs on the web created with Plotly Dash. Calculates a circular tank and returns the maximum stress.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Attached examples

**Test Configuration**:
* RFEM / RSTAB version: 6.02.0034
* Python version: 3.9

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-25 05:49 UTC, OndraMichal requested changes
Nice prototype example using web page.

If we want to go this way a little further then the front-end should look like 'RFEM lite' perhaps. The web page could resemble RFEM with common place for input data, window for 3D render and result tables. This would prepare base for different applications with minimum work to implement new ones.

2022-10-25 05:49 UTC, OndraMichal commented on Examples/TankWebApp/tankWebApp.py
> +    app.run_server(debug=True)
When starting the script, open the web browser with designated port. Something like:
`os.system("start http://127.0.0.1:8050")`
would make it easy for users instead of: 
Dash is running on http://127.0.0.1:8050/

2022-10-25 06:20 UTC, OndraMichal commented
Files: export.vtk and export.obj and forder: export should be excluded from git versioning in .gitignore.

2022-10-27 08:02 UTC, dogukankaratas commented
With latest commit:

- Check for external libraries
- Auto clicked web browser
- New styling items

has added.

Script only works with python version <3.10. We're still waiting dash library to create new release for 3.11.

2022-10-27 08:33 UTC, OndraMichal approved these changes

2022-10-27 08:33 UTC, merged