Ondrej Michal - Types for Timber and Aluminum Design
Dlubal-Software/RFEM_Python_Client pull request #190
Opened 2022-11-08 13:34 UTC by OndraMichal

# Description

Added Types for Timber and Aluminum Design + muliple fixes.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

All current tests and all added tests are passing.

- [x] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM version: 6.02.0037.102.3c6df58020c
* Python version: 3.11.0

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-11-15 12:24 UTC, dogukankaratas commented
New added test works fine. But the change in the name convetion causes problem in the old tests. Now name parameter takes only a string but in some test files they are still a list.

2022-11-15 14:01 UTC, Bjoern-Steinhagen requested changes
Following Unit Tests Failing:
test_loadCombination.py
test_loads.py
test_modalAnalysis_test.py
test_multipleModels.py

Fix for test_loadCombinations.py is commenting within review. Fix for other Unit Test was unclear to me. 

Python: 3.11.0
RFEM: Latest grandmaster (6.02.0039)

2022-11-24 10:29 UTC, Bjoern-Steinhagen commented on RFEM/LoadCasesAndCombinations/loadCombination.py
> +                 name: str = '',
Brilliant! :)

2022-11-24 10:29 UTC, Bjoern-Steinhagen approved these changes

2022-11-24 14:00 UTC, merged