Steel Design ULS Configurations
Dlubal-Software/RFEM_Python_Client pull request #191
Opened 2022-11-09 12:52 UTC by dogukankaratas

# Description

To be able to edit the steel design configurations, SteelDesign folder has created and steelDesignUltimateConfiguration class has added

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM / RSTAB version: 6.02.0035
* Python version: 3.10.8

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-11-10 07:09 UTC, OndraMichal requested changes

2022-11-10 07:09 UTC, OndraMichal commented on RFEM/SteelDesign/steelUltimateConfigurations.py
> +                 user_defined_name: list = [False],
I have just one hint to otherwise flawless execution.
I corrected all instances of 'user_defined_name' in PR#190 to just 'name' and its type from list with redundant info to just string with default ''. The implemetation is then following:
```
if name:
    clientObject.user_defined_name_enabled = True
    clientObject.name = name
```

2022-11-15 12:08 UTC, dogukankaratas commented on RFEM/SteelDesign/steelUltimateConfigurations.py
> +                 user_defined_name: list = [False],
Proposed changes has been made, test file has modified acc. to latest commit.

2022-11-15 13:09 UTC, OndraMichal approved these changes

2022-11-15 13:09 UTC, merged