USGS-RFEM6 Response Spectrum Link
Dlubal-Software/RFEM_Python_Client pull request #205
Opened 2022-12-09 13:44 UTC by dogukankaratas

# Description

The main purpose of this web application is to read the data from USGS Web Service acc. to user input, visualize this data and send the requested response spectrum data to RFEM6. This is requested by our USA branch office members.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Attached examples

**Test Configuration**:
* RFEM / RSTAB version: 6.02.0041
* Python version: 3.10

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-12-12 09:04 UTC, OndraMichal requested changes
After bumping into multiple obstables I was not able to run the script because the execution format was not provided. Apparently I'm missing some arguments. Try run it on clean version of Python from general folder like C: to see and fix all issues.
Errors:
_Connecting to server...
2022-12-12 09:58:01.311
  Warning: to view this Streamlit app on a browser, run it with the following
  command:
    streamlit run d:\Sources\RFEM_Python_Client\Examples\LinkUSGS\UsgsRFEMLink.py [ARGUMENTS]_
    
_FileNotFoundError: [Errno 2] No such file or directory: 'assets/logo_round.png'_

2022-12-19 07:54 UTC, dogukankaratas commented on Examples/LinkUSGS/UsgsRFEMLink.py
> +try:
Done.

2022-12-19 09:13 UTC, dogukankaratas commented on Examples/LinkUSGS/UsgsRFEMLink.py
> +# set page configs and title
Done

2022-12-19 09:14 UTC, dogukankaratas commented on Examples/LinkUSGS/UsgsRFEMLink.py
> +    st.title("USGS-RFEM6 WebService Link")
This issue has occured when I try to run the py file directly. But anyway, this is also creating a runtime error. The correct way to run the example is to type 'streamlit run' in the command prompt.

2022-12-20 06:40 UTC, OndraMichal commented on Examples/LinkUSGS/UsgsRFEMLink.py
> +    st.title("USGS-RFEM6 WebService Link")
Instructions how to run the example needs to be added to describtion or make the code perfectly clear.

2022-12-20 06:48 UTC, OndraMichal requested changes
Instructions how to run the example needs to be added to describtion or make the code perfectly clear.

2023-01-26 11:34 UTC, OndraMichal requested changes
The issue with relative paths was not fixed.
Also, documentation throughout the script is scarce to none.

2023-01-26 11:34 UTC, OndraMichal commented on Examples/LinkUSGS/UsgsRFEMLink.py
> +# to run the website please run the command 'streamlit run UsgsRFEMLink.py' in your command prompt
The cmd command is `python -m streamlit run .\UsgsRFEMLink.py` but still works only from LinkUSGS folder because pictures are defined relatively to this folder not absolutely. See TrussGenerator.py lines 244, 268 etc.:
`dirName = os.path.dirname(__file__)`
`QtGui.QPixmap(dirName+"/sources/logo_round.png")`
Users will have issues running the example. If there is no desire to change it, adding EXACT information into file and README.md would help:

_To run this example, please these follow instructions:
From Command Prompt:
change dir to LinkUSGS: cd .\RFEM_Python_Client\Examples\LinkUSGS\
run the script: python -m streamlit run .\UsgsRFEMLink.py_

2023-01-30 12:13 UTC, dogukankaratas commented
HowTo.md file has added. Unfortunately if I add relative path, there is an error in the Website. So I left it without change.

2023-01-30 14:22 UTC, dogukankaratas commented
Fixed.

2023-01-31 13:12 UTC, merged