combination wizard
Dlubal-Software/RFEM_Python_Client pull request #206
Opened 2022-12-13 12:39 UTC by matchristmann

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM / RSTAB version:
* Python version:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-19 11:56 UTC, dogukankaratas commented on RFEM/LoadCasesAndCombinations/combinationWizard.py
> +
Please create enumeration items in enums.py and get the selection via this class.

![image](https://user-images.githubusercontent.com/61163577/208419941-c341f697-a32a-4976-908a-167a2898497f.png)

2022-12-19 11:56 UTC, dogukankaratas commented on RFEM/LoadCasesAndCombinations/combinationWizard.py
> +                name: str = 'Load Wizard 1',
It'd be nice if we can be consistent with other classes. Please use
`name: str = ''`

2022-12-19 11:56 UTC, dogukankaratas commented on RFEM/LoadCasesAndCombinations/combinationWizard.py
> +            clientObject.user_defined_name_enabled = True
Please use the following if statement here.
```
if name:
    clientObject.user_defined_name_enabled = True
    clientObject.name = name
```

2022-12-19 11:56 UTC, dogukankaratas commented on RFEM/LoadCasesAndCombinations/combinationWizard.py
> +    def StaticAnalysisSettings(
Static methods needs to cover all the instances, which init function has.

2022-12-19 11:56 UTC, dogukankaratas commented on RFEM/LoadCasesAndCombinations/combinationWizard.py
> +        clearAttributes(clientObject)
Please add explanatory comments.

2022-12-20 10:51 UTC, OndraMichal requested changes

2023-01-25 07:36 UTC, OndraMichal approved these changes

2023-01-25 07:36 UTC, merged