Heet ws example script
Dlubal-Software/RFEM_Python_Client pull request #207
Opened 2022-12-20 09:26 UTC by heetrojivadiya

Added Steel Design Example: [SteelHall.py](https://github.com/Dlubal-Software/RFEM_Python_Client/blob/heet-wsExampleScript/Examples/SteelDesign/SteelHall.py)

2023-01-04 12:24 UTC, OndraMichal requested changes

2023-01-05 13:34 UTC, heetrojivadiya commented on Examples/SteelDesign/SteelDesignExcel.py
> +def main():
It is used in Excel VBA. 
<img width="893" alt="Screenshot 2023-01-05 143053" src="https://user-images.githubusercontent.com/108512789/210791739-2959ccb4-73b3-4f92-87ea-ebd8c4473013.png">

2023-01-12 10:50 UTC, OndraMichal approved these changes

2023-01-12 11:53 UTC, OndraMichal approved these changes

2023-01-12 11:54 UTC, merged