Knauer windanalysis
Dlubal-Software/RFEM_Python_Client pull request #214
Opened 2023-01-10 08:53 UTC by aliciaknauer

# Description

Updated wind analysis simulation settings
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM / RSTAB version:
* Python version:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-12 08:49 UTC, OndraMichal requested changes
Few minor issues aside it is nice work 👍

2023-01-12 08:49 UTC, OndraMichal commented on UnitTests/test_windSimulationAnalysisSetting.py
> +@pytest.mark.skipif(GetAddonStatus(Model.clientModel, AddOn.wind_simulation_active)==False, reason="wind_simulaion_active add on has to be checked manually")
Why is test skipped when it is working? Even with Wind Simulation demo.

2023-01-12 08:49 UTC, OndraMichal commented on RFEM/LoadCasesAndCombinations/windSimulationAnalysisSetting.py
> +        if boundary_layers_checked == True:
Statements of this type can be written even simpler: `if boundary_layers_checked:` This automaticaly checks is boundary_layers_checked is True. Testing if boundary_layers_checked is False then looks like `if not boundary_layers_checked:`. I see 7 instances of similar condition. Also try to keep the spaces around operators: 
`consider_surface_roughness==True `
should be 
`consider_surface_roughness == True`

2023-02-07 09:30 UTC, aliciaknauer commented on RFEM/LoadCasesAndCombinations/windSimulationAnalysisSetting.py
> +        if boundary_layers_checked == True:
Hi!  I will change the instances right away.

2023-02-07 09:39 UTC, aliciaknauer commented on UnitTests/test_windSimulationAnalysisSetting.py
> +@pytest.mark.skipif(GetAddonStatus(Model.clientModel, AddOn.wind_simulation_active)==False, reason="wind_simulaion_active add on has to be checked manually")
In the RFEM software you have to have a box checked so that the code works and you can only do it manually. The box is in I think basic object>base data>Add-On and it is called Wind Simulations. And if it is not checked then the test will fail. :)

2023-02-07 09:49 UTC, OndraMichal commented on UnitTests/test_windSimulationAnalysisSetting.py
> +@pytest.mark.skipif(GetAddonStatus(Model.clientModel, AddOn.wind_simulation_active)==False, reason="wind_simulaion_active add on has to be checked manually")
You don't have to check the Add-on manually. `SetAddonStatus(Model.clientModel, AddOn.wind_simulation_active, True)` does the trick.

2023-02-21 13:37 UTC, OndraMichal approved these changes

2023-02-21 14:09 UTC, merged