christmann timber hall design example
Dlubal-Software/RFEM_Python_Client pull request #215
Opened 2023-01-16 10:01 UTC by matchristmann

# Description

This example adds a timber design example using the following webinar as a guidance: 
https://www.dlubal.com/en/support-and-learning/learning/webinars/002410

It should help the user to understand what steps to follow to design his first structure using the client.
The results are exported to an excel file to help with further tasks.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM / RSTAB version:
* Python version:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-19 06:21 UTC, OndraMichal requested changes

2023-01-19 06:21 UTC, OndraMichal commented on Examples/Timber_Design/timber_hall.py
> +from RFEM.LoadCasesAndCombinations.combinationWizard import CombinationWizard
I don't see CombinationWizard in the LoadCasesAndCombinations folder in this branch.

2023-01-19 06:21 UTC, OndraMichal commented on Examples/Timber_Design/timber_hall.py
> +Model.clientModel.service.delete_all()
Model.clientModel.service.begin_modification() is missing here.

2023-01-19 06:21 UTC, OndraMichal commented on Examples/Timber_Design/timber_hall.py
> +PlausibilityCheck(True)
I'm getting Plausibility error here. It seems connected to Effective lengths missing in every member.

From this point on, it was not possible for me to continue the review.

2023-02-01 11:15 UTC, dogukankaratas approved these changes

2023-02-01 12:51 UTC, OndraMichal approved these changes

2023-02-01 12:51 UTC, merged