thickness layer update
Dlubal-Software/RFEM_Python_Client pull request #222
Opened 2023-02-14 11:02 UTC by matchristmann

# Description

Updated thickness.py to support additional settings for layers.
Added required enums for the new functionalities

Setting all options for CLT is not included.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM / RSTAB version:
* Python version:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-16 07:40 UTC, OndraMichal requested changes

2023-02-16 07:40 UTC, OndraMichal commented on RFEM/BasicObjects/thickness.py
> +        if stiffness_reduction and stiffness_modification:
The first part of conditional is redundant because you can nest it under the first one on line 476. It adds to readability.
``` 
if stiffness_reduction:
    clientObject.stiffness_reduction_enabled = stiffness_reduction
    if stiffness_modification:
        clientObject.K33 = stiffness_modification[0][0]
        ...
```

2023-02-16 07:40 UTC, OndraMichal commented on RFEM/BasicObjects/thickness.py
> +        for i in range(len(layers)):
What is the reason behind this update? Is it speed and memory usage? Because `enumerate` still seems to be a little bit more pythonic. If the extra 'j' is the problem, can it simply be omitted? `for i, in enumerate(layers):`

2023-02-16 07:40 UTC, OndraMichal commented on RFEM/BasicObjects/thickness.py
> +            if specify_integration == True:
`if specify_integration:` equals to `if specify_integration == True:`.

2023-02-20 08:05 UTC, matchristmann commented on RFEM/BasicObjects/thickness.py
> +        for i in range(len(layers)):
Yes, the extra ' j ' was the problem, it was not used in the loop.

2023-02-20 09:31 UTC, OndraMichal commented on RFEM/BasicObjects/thickness.py
> +        for i in range(len(layers)):
You didn't have to return it to 'enumerate'. I just wanted you to think about it and learn a little :-)

2023-02-20 09:32 UTC, OndraMichal approved these changes

2023-02-20 09:32 UTC, merged