Knauer US-11518: Types For Timber Design - MoistureClass and ServiceCondition
Dlubal-Software/RFEM_Python_Client pull request #252
Opened 2023-05-03 11:21 UTC by aliciaknauer

# Description

The two functions set_timber_moisture_class and set_timber_service_conditions are implemented here. Since there are some issues with setting the right code, a thorough instruction can be found in every test file on how to test. Because of this reason the pytest.skipif function was added, so it doesn't interfere with existing tests. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM / RSTAB version: 6.02.0060
* Python version: 3.11

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-11 12:29 UTC, heetrojivadiya commented on RFEM/TypesForTimberDesign/timberMoistureClass.py
> +            moisture_class (enum): Timber Moisture Class
Description should be Timber Moisture Class Type Enumeration

2023-05-11 12:29 UTC, heetrojivadiya commented on RFEM/TypesForTimberDesign/timberServiceCondition.py
> +            moisture_service_condition (enum): Timber Service Condition
description should be Timber Moisture Service Condition Type Enumeration

2023-05-11 12:29 UTC, heetrojivadiya commented on RFEM/enums.py
> +class TimberMoistureClassMoistureClass(Enum):
TimberMoistureClassType is better class name

2023-05-11 12:29 UTC, heetrojivadiya commented on RFEM/enums.py
> +class TimberServiceConditionsMoistureServiceCondition(Enum):
TimberMoistureClassType is better class name

2023-05-11 12:29 UTC, heetrojivadiya commented on RFEM/TypesForTimberDesign/timberServiceCondition.py
> +            temperature (enum): Timber Service Conditions Temperature
it would be good to add Enumeration at the end of description for variable type (enum)

2023-05-17 08:56 UTC, OndraMichal requested changes
Hi,
please look at branch MichalOndrej-timberServicesAndMoisture and carefully compare the tests. There is a way to execute the tests properly even if the setters are not in the WS.

2023-05-23 04:57 UTC, merged