Update to latest RFEM
Dlubal-Software/RFEM_Python_Client pull request #258
Opened 2023-05-24 03:22 UTC by OndraMichal

# Description
This change concludes all changes needed so that client can work with latest RFEM ver. 6.02.0065.149.7baec1cb242.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM / RSTAB version: 6.02.0065.149.7baec1cb242
* Python version: 3.11.3

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-24 10:53 UTC, heetrojivadiya requested changes

2023-05-24 10:53 UTC, heetrojivadiya commented on RFEM/TypesForMembers/memberSupport.py
> -        clientObject.nonlinearity = spring_translation_z[1].name
In newer version, name of nonlinearity for translation_z is changed to 'nonlinearity_translational_z' but it is available and accessible with wsdl.

<img width="388" alt="image" src="https://github.com/Dlubal-Software/RFEM_Python_Client/assets/108512789/b5f1cfe1-b968-4573-be36-da1c188f001a">

<img width="528" alt="image" src="https://github.com/Dlubal-Software/RFEM_Python_Client/assets/108512789/ba914cfb-00fa-4959-9c56-2a7b4bf0f975">

2023-05-24 10:53 UTC, heetrojivadiya commented on RFEM/initModel.py
> +#a_socket.settimeout(360)
commented code line should be removed

2023-05-25 16:31 UTC, heetrojivadiya reviewed
changes in new commit seems okay and all new changed unittests are passed. Still two previous comments are not addressed in this commit.

2023-05-26 06:27 UTC, OndraMichal commented on RFEM/TypesForMembers/memberShearPanel.py
> +        #clientObject.member_supports = ConvertToDlString(member_supports)
fixed

2023-05-26 06:28 UTC, OndraMichal commented on RFEM/TypesForMembers/memberSupport.py
> -        clientObject.nonlinearity = spring_translation_z[1].name
Fixed

2023-05-29 06:56 UTC, merged

2023-05-30 10:35 UTC, heetrojivadiya commented on RFEM/BasicObjects/member.py
> -            reference_width_type = MemberReferenceLengthWidthType.REFERENCE_LENGTH_WIDTH_SIXTH,
It should be also updated in docstrings too.