Heet nodal support nonlinearity
Dlubal-Software/RFEM_Python_Client pull request #281
Opened 2023-08-25 14:51 UTC by heetrojivadiya

# Description

Added all nonlinearity types for nodal support. There are still bug for assigning some attributes but I believe that they are from WS core and after fix all assignment will work fine.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM / RSTAB version: RFEM 6.03.0005
* Python version: 3.11

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-10 07:58 UTC, aliciaknauer commented on RFEM/enums.py
> +    Support Partial Activity Along Type Enumeration
Hi,

In the class SupportPartialActivityAroundType, it should be 'around' in the comment.

2023-10-10 08:10 UTC, OndraMichal requested changes

2023-10-10 08:10 UTC, OndraMichal commented on RFEM/TypesForNodes/nodalSupport.py
> -                     spring_x_nonlinearity: list = [NodalSupportNonlinearity.NONLINEARITY_TYPE_NONE, [None], [None]],
Why is this still list or list of lists as descriptions says? All 6 _nonlinearity parameters should be just enum. Make corresponding changes to the description also.

2023-10-10 16:09 UTC, heetrojivadiya commented on RFEM/TypesForNodes/nodalSupport.py
> -                     spring_x_nonlinearity: list = [NodalSupportNonlinearity.NONLINEARITY_TYPE_NONE, [None], [None]],
If the nonlinearity enumeration is partial_activity, diagram or friction_direction then it must be defined with additional list inside main list. I have created unittest for it where I have added example of other nonlinearity type with their additional parameters as list of lists. I also wrote complete description in docstrings when we should to define additional lists and what are the parameters for the same. 

![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/108512789/e68cfa1f-3f93-4594-ac88-82c6a53c116c)

2023-10-10 16:09 UTC, heetrojivadiya commented on RFEM/enums.py
> +    Support Partial Activity Along Type Enumeration
updated

2023-10-11 08:05 UTC, OndraMichal commented on RFEM/TypesForNodes/nodalSupport.py
> -                     spring_x_nonlinearity: list = [NodalSupportNonlinearity.NONLINEARITY_TYPE_NONE, [None], [None]],
ok

2023-10-11 08:05 UTC, OndraMichal approved these changes

2023-10-11 11:41 UTC, merged