update member.py
Dlubal-Software/RFEM_Python_Client pull request #376
Opened 2024-06-05 08:27 UTC by heetrojivadiya

# Description

updated member.py for staticmethod ResultBeam with include/exclude objects.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM version: 6.06.0007
* Python version: 3.11

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-05 12:58 UTC, OndraMichal requested changes
unit tests are OK. 232 passed, 5 skipped in 682.44s (0:11:22)

2024-06-05 12:58 UTC, OndraMichal commented on RFEM/BasicObjects/member.py
> +        if type(include_exclude_objects[0]) == list:
Just a hint. Pythonic way to check type is done with isinstance()) i.e. `if isinstance(list, include_exclude_objects[0]):`

2024-06-05 12:58 UTC, OndraMichal commented on RFEM/BasicObjects/member.py
> +            if include_exclude_objects[0][0] == True:
This type of comparison can be done by `if include_exclude_objects[0][0]:` I find it easier to read.

2024-06-05 12:58 UTC, OndraMichal commented on RFEM/BasicObjects/member.py
> +            include_exclude_objects: list = [[True, True, True], [None, None, None]],
Personaly I would separate it to 2 parameters. include_objects and exclude_objects.

2024-06-05 14:02 UTC, heetrojivadiya commented on RFEM/BasicObjects/member.py
> +            if include_exclude_objects[0][0] == True:
In Python, non-empty strings are considered truthy, meaning they evaluate to True in a boolean context. That means `if include_exclude_objects[0][0]:` condition will be fulfilled by non-empty string which I do not want. So, I intentionally put `if include_exclude_objects[0][0] == True:` here.

2024-06-06 12:17 UTC, OndraMichal approved these changes

2024-06-06 12:18 UTC, merged