Heet surface results adjustment
Dlubal-Software/RFEM_Python_Client pull request #380
Opened 2024-06-11 13:03 UTC by heetrojivadiya

# Description

I updated surfaceResultsAdjustment.py for adjustment type 'USER_DEFINED' and 'ZERO' also updated unittest for it.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM version: 6.06.0007
* Python version: 3.11

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-14 06:36 UTC, OndraMichal requested changes
The test raises assert but not sure if it is caused by the changes.
![image](https://github.com/Dlubal-Software/RFEM_Python_Client/assets/37547309/01f19c18-9d90-4961-a28f-08b5880f369e)

2024-06-14 06:36 UTC, OndraMichal commented on RFEM/SpecialObjects/surfaceResultsAdjustment.py
> +        elif (isinstance(adjustment_type_in_direction_u, list) and adjustment_type_in_direction_u[0].name == 'ZERO') or \
You are repeating this condition on line 208.

2024-06-14 06:36 UTC, OndraMichal commented on RFEM/SpecialObjects/surfaceResultsAdjustment.py
> +            if (not isinstance(adjustment_type_in_direction_u, list) and adjustment_type_in_direction_u.name == 'CONTACT_STRESS_AREA') or \
You are doing the check `isinstance(adjustment_type_in_direction_u, list)` 5x and the second one 4x. You can either create variable adj_type_in_dir_u = True/False to make it more readable and faster or put all applicable code under one condition to avoiding repeating it.

2024-06-14 06:36 UTC, OndraMichal commented on RFEM/SpecialObjects/surfaceResultsAdjustment.py
> +        if (isinstance(adjustment_type_in_direction_u, list) and adjustment_type_in_direction_u[0].name == 'ZERO') and \
Try to avoid repeating long lines of code. What about this statement? Isn't it more readable?
```
u_dir_zero = isinstance(adjustment_type_in_direction_u, list) and adjustment_type_in_direction_u[0].name == 'ZERO'
v_dir_zero = isinstance(adjustment_type_in_direction_v, list) and adjustment_type_in_direction_v[0].name == 'ZERO'

if u_dir_zero and v_dir_zero:
     raise TypeError("WARNING: Surface result adjustment type in both directon can not be 'ZERO'.")
elif u_dir_zero:
    child_items_zero = adjustment_type_in_direction_u[1]
elif v_dir_zero:
    child_items_zero = adjustment_type_in_direction_v[1]
```

2024-06-14 06:36 UTC, OndraMichal commented on RFEM/SpecialObjects/surfaceResultsAdjustment.py
> +
Why is deleteEmptyAttributes() missing?
```
# Delete None attributes for improved performance
        deleteEmptyAttributes(clientObject)
```

2024-06-14 09:56 UTC, heetrojivadiya commented on RFEM/SpecialObjects/surfaceResultsAdjustment.py
> +
iter(obj) in deleteEmptyAttributes() gives the non tuple set due to nested dictionary in adjust_in_zero/_direction_u/v. So it was giving below error.  
```
iter(obj) output:

('no', 1) <class 'tuple'>
('user_defined_name_enabled', True) <class 'tuple'>
('name', 'SRA1') <class 'tuple'>
('surfaces', '') <class 'tuple'>
('shape', 'SHAPE_RECTANGLE') <class 'tuple'>
('dimension_1', 1.1) <class 'tuple'>
('dimension_2', 1.2) <class 'tuple'>
('angular_rotation', 0) <class 'tuple'>
('center_position', None) <class 'tuple'>
('center_position_x', 0) <class 'tuple'>
('center_position_y', 0) <class 'tuple'>
('center_position_z', 0) <class 'tuple'>
('polygon_points', None) <class 'tuple'>
('adjustment_type_in_direction_u', 'AVERAGING_OF_MY_MXY_VY_NY_NXY') <class 'tuple'>
('adjustment_type_in_direction_v', 'USER_DEFINED') <class 'tuple'>
('results_to_adjust_contact_stress_area', None) <class 'tuple'>
('projection_in_direction_type', 'PERPENDICULAR') <class 'tuple'>
('vector_of_projection_in_direction_coordinates', None) <class 'tuple'>
('vector_of_projection_in_direction_coordinates_x', None) <class 'tuple'>
('vector_of_projection_in_direction_coordinates_y', None) <class 'tuple'>
('vector_of_projection_in_direction_coordinates_z', None) <class 'tuple'>
('comment', '') <class 'tuple'>
('results_to_adjust_in_direction_u', None) <class 'tuple'>
('results_to_adjust_in_direction_v', <suds.sudsobject.array_of_surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items object at 0x000001E68BE1FA90>) <class 'tuple'>
('item', [<suds.sudsobject.surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items object at 0x000001E68BE23B10>]) <class 'tuple'>
(surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items){
   surface_results_adjustment_results_to_adjust_in_direction_v =
      (surface_results_adjustment_results_to_adjust_in_direction_v_row){
         no = 0
         row = "main_quantity_property_id_surface_results_basic_internal_forces=false"
      }
   child_items =
      (array_of_surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items){
         item[] =
            (surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items){
               surface_results_adjustment_results_to_adjust_in_direction_v =
                  (surface_results_adjustment_results_to_adjust_in_direction_v_row){
                     no = 0
                     row = "main_quantity_property_id_surface_results_basic_internal_forces_mx=false"
                  }
            },
            (surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items){
               surface_results_adjustment_results_to_adjust_in_direction_v =
                  (surface_results_adjustment_results_to_adjust_in_direction_v_row){
                     no = 1
                     row = "main_quantity_property_id_surface_results_basic_internal_forces_my=true"
                  }
            },
            (surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items){
               surface_results_adjustment_results_to_adjust_in_direction_v =
                  (surface_results_adjustment_results_to_adjust_in_direction_v_row){
                     no = 2
                     row = "main_quantity_property_id_surface_results_basic_internal_forces_mxy=true"
                  }
            },
            (surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items){
               surface_results_adjustment_results_to_adjust_in_direction_v =
                  (surface_results_adjustment_results_to_adjust_in_direction_v_row){
                     no = 3
                     row = "main_quantity_property_id_surface_results_basic_internal_forces_vx=true"
                  }
            },
            (surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items){
               surface_results_adjustment_results_to_adjust_in_direction_v =
                  (surface_results_adjustment_results_to_adjust_in_direction_v_row){
                     no = 4
                     row = "main_quantity_property_id_surface_results_basic_internal_forces_vy=false"
                  }
            },
            (surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items){
               surface_results_adjustment_results_to_adjust_in_direction_v =
                  (surface_results_adjustment_results_to_adjust_in_direction_v_row){
                     no = 5
                     row = "main_quantity_property_id_surface_results_basic_internal_forces_nx=true"
                  }
            },
            (surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items){
               surface_results_adjustment_results_to_adjust_in_direction_v =
                  (surface_results_adjustment_results_to_adjust_in_direction_v_row){
                     no = 6
                     row = "main_quantity_property_id_surface_results_basic_internal_forces_ny=false"
                  }
            },
            (surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items){
               surface_results_adjustment_results_to_adjust_in_direction_v =
                  (surface_results_adjustment_results_to_adjust_in_direction_v_row){
                     no = 7
                     row = "main_quantity_property_id_surface_results_basic_internal_forces_nxy=true"
                  }
            },
      }
 } <class 'suds.sudsobject.surface_results_adjustment_results_to_adjust_in_direction_v_and_child_items'>
('results_to_adjust_zero', None) <class 'tuple'>
('id_for_export_import', None) <class 'tuple'>
('metadata_for_export_import', None) <class 'tuple'>
```

```
error: 
File "c:\Users\RojivadivaH\Documents\GitHub\RFEM_Python_Client\Examples\Cantilever\Demo1.py", line 89, in <module>
    SurfaceResultsAdjustment(1, SurfaceResultsAdjustmentShape.SHAPE_RECTANGLE, [1.1,1.2,0], [0,0,0], SurfaceResultsAdjustmentType.AVERAGING_OF_MY_MXY_VY_NY_NXY, [SurfaceResultsAdjustmentType.USER_DEFINED, childItems1], name='SRA1')
  File "c:\Users\RojivadivaH\Documents\GitHub\RFEM_Python_Client\Examples\Cantilever/../..\RFEM\SpecialObjects\surfaceResultsAdjustment.py", line 270, in __init__
    deleteEmptyAttributes(clientObject)
  File "c:\Users\RojivadivaH\Documents\GitHub\RFEM_Python_Client\Examples\Cantilever/../..\RFEM\initModel.py", line 307, in deleteEmptyAttributes
    i[1] = deleteEmptyAttributes(i[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RojivadivaH\Documents\GitHub\RFEM_Python_Client\Examples\Cantilever/../..\RFEM\initModel.py", line 307, in deleteEmptyAttributes
    i[1] = deleteEmptyAttributes(i[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RojivadivaH\Documents\GitHub\RFEM_Python_Client\Examples\Cantilever/../..\RFEM\initModel.py", line 310, in deleteEmptyAttributes
    i[1] = deleteEmptyAttributes(i[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RojivadivaH\Documents\GitHub\RFEM_Python_Client\Examples\Cantilever/../..\RFEM\initModel.py", line 307, in deleteEmptyAttributes
    i[1] = deleteEmptyAttributes(i[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RojivadivaH\Documents\GitHub\RFEM_Python_Client\Examples\Cantilever/../..\RFEM\initModel.py", line 300, in deleteEmptyAttributes
    elif i[1] is None or i[1] == "":
         ~^^^
  File "C:\Users\RojivadivaH\AppData\Roaming\Python\Python311\site-packages\suds\sudsobject.py", line 156, in __getitem__
    name = self.__keylist__[int(name)]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^
IndexError: list index out of range
```

by adding `or not isinstance(i, tuple)` at [line#295 in initModel.py](https://github.com/Dlubal-Software/RFEM_Python_Client/blob/main/RFEM/initModel.py#L295), it solved the error.

2024-06-17 07:02 UTC, OndraMichal approved these changes
Nice work.

2024-06-17 07:35 UTC, merged