Temporary fix for load combinations
dlubal-software/RFEM_Python_Client pull request #404
Opened 2024-11-19 13:47 UTC by Rebecca-Coding21

# Description

I fixed the example SteelDesignExcel.py again. Because of a bug in WS core the load combinations are not generated automatically which leads to an error during steel design calculation.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests
- [ ] Attached examples

**Test Configuration**:
* RFEM version: 6.08.0007
* Python version: 3.13.0

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-19 14:29 UTC, heetrojivadiya requested changes
Please update.

2024-12-11 07:47 UTC, heetrojivadiya requested changes

2024-12-11 07:47 UTC, heetrojivadiya commented on Examples/SteelDesign/SteelDesignExcel.py
> +            index = lst.index('SteelHallExcel')
I am getting error due to this line. It should be lst[0] instead of lst.
```index = lst[0].index('SteelHallExcel')```

![image](https://github.com/user-attachments/assets/b32b5f35-c8c4-4b2e-9ec2-5a77fa4765e0)

2024-12-16 10:03 UTC, Rebecca-Coding21 commented on Examples/SteelDesign/SteelDesignExcel.py
> +    #Model.clientModel.service.generate_load_cases_and_combinations()
The bug was resolved. Generation of load combinations is working now. (Version 6.08.0010)

2025-02-07 13:42 UTC, jarabroz approved these changes

2025-02-07 13:43 UTC, merged