Ondrej Michal Add options to dialog
Dlubal-Software/RFEM_Python_Client pull request #71
Opened 2021-11-05 06:11 UTC by OndraMichal

US-8506: Web Services: Python: Improvement in initialization of connection with RFEM6

Description:
Purpose of this task is to add new options to input dialogue to enable use already existing models in RFEM or create new one. Edit name of the new model. If existing one is selected then enable deleting results and reset of the model. This envolves changes in initModle.py file to enable loading of existing models befor showing dialogue and then effective use of clientModel ( by creating Model class).

2021-11-08 13:05 UTC, dogukankaratas requested changes

2021-11-08 13:05 UTC, dogukankaratas commented on UnitTests/test_basicObjects.py
Model(model_name = 'basicobjects_test')

2021-11-08 13:05 UTC, dogukankaratas commented on main.py
> +    Model(hall_width_L, hall_height_h_o, hall_height_h_m, number_frames, frame_spacing, new_model, model_name, delete, reset)
Acc. to previous suggestions, line 28 should be change as;

_Model(new_model, model_name, delete, reset)_

2021-11-15 13:57 UTC, OndraMichal commented on RFEM/initModel.py
> +        print('Geometry...')
Well we can print what ever we agree on. By this messages I wanted to comunicate to user, which part of script is running. If Ready seems more appropriate, we can change it. Maybe we should vote on things like that. There is no 100% correct solution.

2021-11-16 08:32 UTC, OndraMichal commented on Examples/CantileverQt/Main.py
>          # RFEM 6
solved

2021-11-16 08:44 UTC, OndraMichal commented on Examples/DesignSituations_Test.py
corrected.
Error: Invalid design situation type.' still persist. Out of the scope of this code review.

2021-11-16 08:44 UTC, OndraMichal commented on Examples/Free_Load_Test.py
solved

2021-11-16 08:51 UTC, OndraMichal commented on Examples/GlobalParameters_Test.py
solved
suds.WebFault: Server raised fault: 'Enumeration item 'DEFINITION_TYPE_OPTIMIZATION' not found.'  still persist.

2021-11-16 08:58 UTC, OndraMichal commented on Examples/LineLoads_Test.py
solved. also corrected TabError: inconsistent use of tabs and spaces in indentation

2021-11-16 09:05 UTC, OndraMichal commented on Examples/LoadCases_Test.py
solved

2021-11-16 09:08 UTC, OndraMichal commented on Examples/LoadDistributionSurface_Test.py
solved
suds.TypeNotFound: Type not found: 'load_distribution_direction' still persist.

2021-11-16 09:09 UTC, OndraMichal commented on Examples/MemberLoad_test.py
solved

2021-11-16 09:21 UTC, OndraMichal commented on Examples/MemberSetLoad_test.py
solved

2021-11-16 09:23 UTC, OndraMichal commented on Examples/MembraneSurface_Test.py
solved

2021-11-16 09:48 UTC, OndraMichal commented on Examples/MembraneWithoutTensionSurface_Test.py
solved
Assert still persist.

2021-11-16 09:49 UTC, OndraMichal commented on Examples/NodalLoad_test.py
solved.
NameError: name 'ModalSolutionMethod' is not defined still persist.

2021-11-16 09:51 UTC, OndraMichal commented on Examples/RigidSurface_Test.py
solved

2021-11-16 09:57 UTC, OndraMichal commented on Examples/SpectralSettings_test.py
>  	#spectral analysis is not yet supported in released RFEM6 in WS
solved. suds.TypeNotFound: Type not found: 'ns0:spectral_analysis_settings' still persist.

2021-11-16 09:58 UTC, OndraMichal commented on Examples/StandardSurface_Test.py
solved

2021-11-16 09:59 UTC, OndraMichal commented on Examples/SurfaceLoad_test.py
solved

2021-11-16 10:00 UTC, OndraMichal commented on Examples/SurfaceSetLoad_test.py
solved

2021-11-16 10:01 UTC, OndraMichal commented on Examples/Thickness_Test.py
solved

2021-11-16 10:02 UTC, OndraMichal commented on Examples/WithoutThicknessSurface_Test.py
solved

2021-11-16 10:04 UTC, OndraMichal commented on Examples/modalAnalysis_test.py
>      # modal analysis not yet implemmented in released RFEM6
solved. NameError: name 'ModalSolutionMethod' is not defined still persist.

2021-11-16 10:04 UTC, OndraMichal commented on RFEM/BasicObjects/material.py
> +class Material(Model):
inheritance removed

2021-11-16 10:06 UTC, OndraMichal commented on RFEM/initModel.py
> +    def __init__(self,
solved

2021-11-16 10:08 UTC, OndraMichal commented on UnitTests/test_basicObjects.py
solved

2021-11-16 12:09 UTC, dogukankaratas commented on Examples/DesignSituations_Test.py
Björn is taking care of that error. @Bjoern-Steinhagen

2021-11-16 15:08 UTC, dogukankaratas approved these changes
- Conflicts should be solven.

2021-12-01 13:45 UTC, merged